name: lol

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Run a one-line script
        run: ls -halt

      - name: Run a one-line script
        run: sleep infinity
